spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    com:
      DataSource: Trace